export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MESSAGE = 'GET_MESSAGE'
export const SET_REPLY = 'SET_REPLY'
export const SET_MESSAGE = 'SET_MESSAGE'
export const ADD_MESSAGE_FILE = 'ADD_MESSAGE_FILE'
